FROM node:lts-alpine3.17 AS Development

ENV NODE_ENV=development

WORKDIR /react_app

COPY ["package.json",  "."]

RUN npm install

COPY [".", "."]

EXPOSE 3001

# CMD [ "npm", "run", "dev", "--", "--host" ]

CMD [ "npm", "run", "dev" ]